- name: Deploy to Tomcat
  hosts: web
  become: yes
  connection: local
  tasks:
    - name: Copy WAR to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/exp5/target/Maven-AnsibleWebApp.war"
        dest: "/opt/tomcat/webapps/"
        remote_src: no
